// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.Cloud.ListServerService.IListServerClientApi.onServerListUpdated")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ApiConnector._onServerListUpdated")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ApiConnector.ApiAddress")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ApiConnector.ApiKey")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.CustomDataHelper.MaxCustomData")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.KeyValue.MaxKeySize")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.KeyValue.MaxValueSize")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.ListServerClientApi._onServerListUpdated")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.ListServerServerApi._pingCoroutine")]
[assembly: SuppressMessage("Style", "IDE0032:Use auto property", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.ListServerServerApi.added")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.ListServerServerApi.MaxPingFails")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.ListServerService.ListServerServerApi.PingInterval")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.RequestCreator.DELETE")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.RequestCreator.GET")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.RequestCreator.PATCH")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.Cloud.RequestCreator.POST")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.Extensions.IsOk(UnityEngine.Networking.UnityWebRequest)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.CustomDataHelper.ToDictionary(Mirror.Cloud.ListServerService.KeyValue[])~System.Collections.Generic.Dictionary{System.String,System.String}")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.CustomDataHelper.ToKeyValueArray(System.Collections.Generic.Dictionary{System.String,System.String})~Mirror.Cloud.ListServerService.KeyValue[]")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerClientApi.#ctor(Mirror.Cloud.ICoroutineRunner,Mirror.Cloud.IRequestCreator,Mirror.Cloud.ServerListEvent)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerClientApi.getServerList~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerClientApi.GetServerList")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerClientApi.Shutdown")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerClientApi.StartGetServerListRepeat(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.addServer(Mirror.Cloud.ListServerService.ServerJson)~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Style", "IDE0061:Use expression body for local functions", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.addServer(Mirror.Cloud.ListServerService.ServerJson)~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Style", "IDE0061:Use expression body for local functions", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.ping~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.ping~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.removeServer~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.removeServerWithoutCoroutine")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.stopPingCoroutine")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.updateServer(Mirror.Cloud.ListServerService.PartialServerJson)~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.ListServerServerApi.UpdateServer(Mirror.Cloud.ListServerService.ServerJson)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.ListServerService.PartialServerJson.Validate")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.Logger.Log(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.Logger.LogError(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.Logger.LogWarning(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.RequestCreator.CreateUri(System.String)~System.Uri")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.RequestCreator.CreateWebRequest(System.String,System.String,System.String)~UnityEngine.Networking.UnityWebRequest")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.RequestCreator.Delete(System.String)~UnityEngine.Networking.UnityWebRequest")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.RequestCreator.Get(System.String)~UnityEngine.Networking.UnityWebRequest")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.RequestCreator.SendRequest(UnityEngine.Networking.UnityWebRequest,Mirror.Cloud.RequestSuccess,Mirror.Cloud.RequestFail)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.RequestCreator.SendRequestEnumerator(UnityEngine.Networking.UnityWebRequest,Mirror.Cloud.RequestSuccess,Mirror.Cloud.RequestFail)~System.Collections.IEnumerator")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.UnityEqualCheckExtension.IsNotNull(Mirror.Cloud.IUnityEqualCheck)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S2219:Runtime type checking should be simplified", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.UnityEqualCheckExtension.IsNotNull(Mirror.Cloud.IUnityEqualCheck)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S2219:Runtime type checking should be simplified", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.UnityEqualCheckExtension.IsNull(Mirror.Cloud.IUnityEqualCheck)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.Cloud.UnityEqualCheckExtension.IsNull(Mirror.Cloud.IUnityEqualCheck)~System.Boolean")]
