// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Critical Code Smell", "S2223:Non-constant static fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkClient.connectState")]
[assembly: SuppressMessage("Critical Code Smell", "S2223:Non-constant static fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkClient.OnConnectedEvent")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkClient.OnConnectedEvent")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkClient.OnDisconnectedEvent")]
[assembly: SuppressMessage("Critical Code Smell", "S2223:Non-constant static fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkClient.OnDisconnectedEvent")]
[assembly: SuppressMessage("Critical Code Smell", "S2223:Non-constant static fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkClient.ready")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.AddPlayer~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ApplySpawnPayload(Mirror.NetworkIdentity,Mirror.SpawnMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.CheckForLocalPlayer(Mirror.NetworkIdentity)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ClearNullFromSpawned")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.Connect(System.String)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.Connect(System.Uri)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ConnectHost")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ConnectHost")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ConnectLocalServer")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ConnectLocalServer")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.DestroyObject(System.UInt32)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.Disconnect")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.DisconnectLocalServer")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.DisconnectLocalServer")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.InternalAddPlayer(Mirror.NetworkIdentity)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.InternalAddPlayer(Mirror.NetworkIdentity)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnHostClientObjectDestroy(Mirror.ObjectDestroyMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnHostClientObjectDestroy(Mirror.ObjectDestroyMessage)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnHostClientObjectDestroy(Mirror.ObjectDestroyMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnHostClientObjectHide(Mirror.ObjectHideMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnObjectSpawnFinished(Mirror.ObjectSpawnFinishedMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnObjectSpawnStarted(Mirror.ObjectSpawnStartedMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnRPCMessage(Mirror.RpcMessage)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnRPCMessage(Mirror.RpcMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnSpawn(Mirror.SpawnMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnUpdateVarsMessage(Mirror.UpdateVarsMessage)")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.OnUpdateVarsMessage(Mirror.UpdateVarsMessage)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.Ready~System.Boolean")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.Ready~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0039:Use local function", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterHandler``1(System.Action{``0},System.Boolean)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterPrefab(UnityEngine.GameObject,Mirror.SpawnDelegate,Mirror.UnSpawnDelegate)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterPrefab(UnityEngine.GameObject,Mirror.SpawnHandlerDelegate,Mirror.UnSpawnDelegate)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterPrefab(UnityEngine.GameObject,Mirror.SpawnHandlerDelegate,Mirror.UnSpawnDelegate)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterPrefab(UnityEngine.GameObject,System.Guid,Mirror.SpawnDelegate,Mirror.UnSpawnDelegate)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterPrefab(UnityEngine.GameObject,System.Guid,Mirror.SpawnHandlerDelegate,Mirror.UnSpawnDelegate)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterPrefab(UnityEngine.GameObject,System.Guid,Mirror.SpawnHandlerDelegate,Mirror.UnSpawnDelegate)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterPrefabIdentity(Mirror.NetworkIdentity)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.RegisterSpawnHandler(System.Guid,Mirror.SpawnHandlerDelegate,Mirror.UnSpawnDelegate)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ReplaceHandler``1(System.Action{``0},System.Boolean)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ReplaceHandler``1(System.Action{``0},System.Boolean)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.ReplaceHandler``1(System.Action{Mirror.NetworkConnection,``0},System.Boolean)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.SpawnPrefab(Mirror.SpawnMessage)~Mirror.NetworkIdentity")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkClient.SpawnSceneObject(Mirror.SpawnMessage)~Mirror.NetworkIdentity")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.active")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.connection")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.isConnected")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.isConnecting")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.isLocalClient")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.localPlayer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.readyConnection")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.readyConnection")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkClient.serverIp")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "type", Target = "~T:Mirror.NetworkClient")]
