// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.BufferBucket._current")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.Log.DEBUG")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.Log.SIMPLEWEB_LOG_ENABLED")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.ServerHandshake.GetSize")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.ServerHandshake.KeyHeaderString")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.ServerHandshake.KeyLength")]
[assembly: SuppressMessage("Minor Code Smell", "S3604:Member initializer values should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.ServerHandshake.maxHttpHeaderSize")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.ServerHandshake.MergedKeyLength")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.ServerHandshake.ResponseLength")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.SimpleWebTransport._logLevels")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.SimpleWeb.WebSocketServer._idCounter")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ArrayBuffer.CopyFrom(System.ArraySegment{System.Byte})")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ArrayBuffer.Dispose")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ArrayBuffer.SetReleasesRequired(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ArrayBuffer.ToSegment~System.ArraySegment{System.Byte}")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ClientSslHelper.ValidateServerCertificate(System.Object,System.Security.Cryptography.X509Certificates.X509Certificate,System.Security.Cryptography.X509Certificates.X509Chain,System.Net.Security.SslPolicyErrors)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.Log.BufferToString(System.Byte[],System.Int32,System.Nullable{System.Int32})~System.String")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.Log.Exception(System.Exception)")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.Message.#ctor(Mirror.SimpleWeb.EventType)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.MessageProcessor.GetOpcode(System.Byte[])~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.MessageProcessor.ToggleMask(System.Byte[],System.Int32,System.Int32,System.Byte[],System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ReceiveLoop.GetCloseCode(System.Byte[],System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ReceiveLoop.GetCloseMessage(System.Byte[],System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SendLoop.MaskHelper.Dispose")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ServerHandshake.AcceptHandshake(System.IO.Stream,System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ServerHandshake.AppendGuid(System.Byte[])")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ServerHandshake.ReadToEndForHandshake(System.IO.Stream)~System.String")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ServerSslHelper.acceptClient(System.Object,System.Security.Cryptography.X509Certificates.X509Certificate,System.Security.Cryptography.X509Certificates.X509Chain,System.Net.Security.SslPolicyErrors)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebClient.Create(System.Int32,System.Int32,Mirror.SimpleWeb.TcpConfig)~Mirror.SimpleWeb.SimpleWebClient")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebServer.GetClientAddress(System.Int32)~System.String")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebServer.KickClient(System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.Available~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.Awake")]
[assembly: SuppressMessage("Critical Code Smell", "S927:Parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ClientConnect(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ClientConnected~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ClientDisconnect")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ClientEarlyUpdate")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.GetMaxPacketSize(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ServerActive~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ServerEarlyUpdate")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ServerGetClientAddress(System.Int32)~System.String")]
[assembly: SuppressMessage("Minor Code Smell", "S3626:Jump statements should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebTransport.ServerSend(System.Int32,System.Int32,System.ArraySegment{System.Byte})")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.Utils.CheckForInterupt")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketClientStandAlone.Connect(System.Uri)")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketClientStandAlone.ConnectAndReceiveLoop(System.Uri)")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketClientWebGl.#ctor(System.Int32,System.Int32)")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketServer.acceptLoop")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketServer.Listen(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketServer.acceptLoop")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebClient.onConnect")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebClient.onData")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebClient.onDisconnect")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebClient.onError")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebServer.onConnect")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebServer.onData")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebServer.onDisconnect")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.SimpleWeb.SimpleWebServer.onError")]
[assembly: SuppressMessage("Style", "IDE0048:Add parentheses for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.MessageProcessor.ToggleMask(System.Byte[],System.Int32,System.Byte[],System.Int32,System.Int32,System.Byte[],System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ReadHelper.Read(System.IO.Stream,System.Byte[],System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0048:Add parentheses for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ReceiveLoop.GetCloseCode(System.Byte[],System.Int32)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ReceiveLoop.ReadOneMessage(Mirror.SimpleWeb.ReceiveLoop.Config,System.Byte[])")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.ServerSslHelper.acceptClient(System.Object,System.Security.Cryptography.X509Certificates.X509Certificate,System.Security.Cryptography.X509Certificates.X509Chain,System.Net.Security.SslPolicyErrors)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebJSLib.Connect(System.String,System.Action{System.Int32},System.Action{System.Int32},System.Action{System.Int32,System.IntPtr,System.Int32},System.Action{System.Int32})~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebJSLib.Disconnect(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebJSLib.IsConnected(System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.SimpleWebJSLib.Send(System.Int32,System.Byte[],System.Int32,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketClientWebGl.onClose")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketClientWebGl.onErr")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketClientWebGl.onMessage(System.IntPtr,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.SimpleWeb.WebSocketClientWebGl.onOpen")]
