// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.GetSyncVarGameObject(System.UInt32,UnityEngine.GameObject@)~UnityEngine.GameObject")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.getSyncVarHookGuard(System.UInt64)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.IsDirty~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.OnSerialize(Mirror.NetworkWriter,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.OnSerialize(Mirror.NetworkWriter,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0071:Simplify interpolation", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SendCommandInternal(System.Type,System.String,Mirror.NetworkWriter,System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.setSyncVarHookGuard(System.UInt64,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.connectionToClient")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.connectionToServer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.hasAuthority")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.isClient")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.isClientOnly")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.isLocalPlayer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.isServer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.isServerOnly")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.netId")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.netIdentity")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkBehaviour.syncVarDirtyBits")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Mirror.NetworkIdentity.clientAuthorityCallback")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkIdentity.networkBehavioursCache")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkIdentity.networkBehavioursCache")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.assetId")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.connectionToClient")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.connectionToServer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.hasAuthority")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.isClient")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.isClientOnly")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.isLocalPlayer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.isServer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.isServerOnly")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.netId")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.visibility")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkIdentity._connectionToClient")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkIdentity._NetworkBehaviours")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Mirror.NetworkIdentity.m_AssetId")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.getSyncVarHookGuard(System.UInt64)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.NetworkBehaviourSyncVar.Equals(Mirror.NetworkBehaviour.NetworkBehaviourSyncVar)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.NetworkBehaviourSyncVar.Equals(System.UInt32,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.NetworkBehaviourSyncVar.ToString~System.String")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SerializeSyncVars(Mirror.NetworkWriter,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SetDirtyBit(System.UInt64)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SetSyncVar``1(``0,``0@,System.UInt64)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SetSyncVarGameObject(UnityEngine.GameObject,UnityEngine.GameObject@,System.UInt64,System.UInt32@)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SetSyncVarNetworkBehaviour``1(``0,``0@,System.UInt64,Mirror.NetworkBehaviour.NetworkBehaviourSyncVar@)")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SetSyncVarNetworkBehaviour``1(``0,``0@,System.UInt64,Mirror.NetworkBehaviour.NetworkBehaviourSyncVar@)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SetSyncVarNetworkIdentity(Mirror.NetworkIdentity,Mirror.NetworkIdentity@,System.UInt64,System.UInt32@)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkBehaviour.SyncVarEqual``1(``0,``0@)~System.Boolean")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.AddObserver(Mirror.NetworkConnection)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.AssignSceneID")]
[assembly: SuppressMessage("Major Bug", "S2583:Conditionally executed code should be reachable", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.GetCommandInfo(System.Int32,System.Int32)~Mirror.RemoteCalls.CommandInfo")]
[assembly: SuppressMessage("Major Bug", "S2583:Conditionally executed code should be reachable", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.HandleRemoteCall(System.Int32,System.Int32,Mirror.MirrorInvokeType,Mirror.NetworkReader,Mirror.NetworkConnectionToClient)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.OnDeserializeSafely(Mirror.NetworkBehaviour,Mirror.NetworkReader,System.Boolean)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.OnSerializeAllSafely(System.Boolean,Mirror.NetworkWriter,System.Int32@,Mirror.NetworkWriter,System.Int32@)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.OnSerializeSafely(Mirror.NetworkBehaviour,Mirror.NetworkWriter,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Minor Code Smell", "S3241:Methods should not return values that are never used", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.OnSerializeSafely(Mirror.NetworkBehaviour,Mirror.NetworkWriter,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.OnStartClient")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.OnStartServer")]
[assembly: SuppressMessage("Style", "IDE0063:Use simple 'using' statement", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.SendUpdateVarsMessage")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.SetSceneIdSceneHashPartInternal")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.SetupIDs")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~P:Mirror.NetworkIdentity.assetId")]
[assembly: SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "type", Target = "~T:Mirror.NetworkIdentity")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for methods", Justification = "<Pending>", Scope = "member", Target = "~M:Mirror.NetworkIdentity.RemoveObserverInternal(Mirror.NetworkConnection)")]
