// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<Pending>", Scope = "member", Target = "~F:Telepathy.MagnificentReceivePipe.pool")]
[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<Pending>", Scope = "member", Target = "~F:Telepathy.MagnificentReceivePipe.queueCounter")]
[assembly: SuppressMessage("Major Code Smell", "S2933:Fields that are only assigned in the constructor should be \"readonly\"", Justification = "<Pending>", Scope = "member", Target = "~F:Telepathy.MagnificentSendPipe.pool")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Client.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Client.Connect(System.String,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Client.ReceiveThreadFunction(Telepathy.ClientConnectionState,System.String,System.Int32,System.Int32,System.Boolean,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Client.ReceiveThreadFunction(Telepathy.ClientConnectionState,System.String,System.Int32,System.Int32,System.Boolean,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.ClientConnectionState.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.ClientConnectionState.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Common.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Common.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.ConnectionState.#ctor(System.Net.Sockets.TcpClient,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentReceivePipe.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentReceivePipe.#ctor(System.Int32)")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentReceivePipe.Clear")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentReceivePipe.Count(System.Int32)~System.Int32")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentReceivePipe.Enqueue(System.Int32,Telepathy.EventType,System.ArraySegment{System.Byte})")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentReceivePipe.TryDequeue~System.Boolean")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentReceivePipe.TryPeek(System.Int32@,Telepathy.EventType@,System.ArraySegment{System.Byte}@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentSendPipe.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentSendPipe.#ctor(System.Int32)")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentSendPipe.Clear")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentSendPipe.DequeueAndSerializeAll(System.Byte[]@,System.Int32@)~System.Boolean")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.MagnificentSendPipe.Enqueue(System.ArraySegment{System.Byte})")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.NetworkStreamExtensions.ReadExactly(System.Net.Sockets.NetworkStream,System.Byte[],System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0021:Use expression body for constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Pool`1.#ctor(System.Func{`0})")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Server.#ctor(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Server.Listen(System.Int32)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Server.Send(System.Int32,System.ArraySegment{System.Byte})~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Server.Start(System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Major Code Smell", "S108:Nested blocks of code should not be left empty", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Server.Stop")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.ThreadFunctions.ReadMessageBlocking(System.Net.Sockets.NetworkStream,System.Int32,System.Byte[],System.Byte[],System.Int32@)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.ThreadFunctions.ReceiveLoop(System.Int32,System.Net.Sockets.TcpClient,System.Int32,Telepathy.MagnificentReceivePipe,System.Int32)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.ThreadFunctions.ReceiveLoop(System.Int32,System.Net.Sockets.TcpClient,System.Int32,Telepathy.MagnificentReceivePipe,System.Int32)")]
[assembly: SuppressMessage("Major Code Smell", "S1066:Collapsible \"if\" statements should be merged", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.ThreadFunctions.SendLoop(System.Int32,System.Net.Sockets.TcpClient,Telepathy.MagnificentSendPipe,System.Threading.ManualResetEvent)")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~P:Telepathy.MagnificentReceivePipe.PoolCount")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~P:Telepathy.MagnificentReceivePipe.TotalCount")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~P:Telepathy.MagnificentSendPipe.Count")]
[assembly: SuppressMessage("Critical Bug", "S2551:Shared resources should not be used for locking", Justification = "<Pending>", Scope = "member", Target = "~P:Telepathy.MagnificentSendPipe.PoolCount")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Telepathy.MagnificentReceivePipe.pool")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Telepathy.MagnificentReceivePipe.queueCounter")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:Telepathy.MagnificentSendPipe.pool")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Server.GetClientAddress(System.Int32)~System.String")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Telepathy.Server.NextConnectionId~System.Int32")]
